artifact_location: file:///home/boume/data-science-toolkit/air-quality/notebooks/session3/mlruns_registry_demo/633445724452652697
creation_time: 1790507274712
experiment_id: '633445724452652697'
last_update_time: 1790507274712
lifecycle_stage: active
name: registry_demo
