aliases: []
creation_timestamp: 1790507281630
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1790507281630
metrics: null
model_id: m-905794ee8233405cb3348b16fbf235cb
name: toy_model
params: null
run_id: fd8d488bc6d64c5d9612453b9bb1ffb8
run_link: null
source: models:/m-905794ee8233405cb3348b16fbf235cb
status: READY
status_message: null
storage_location: file:///home/boume/data-science-toolkit/air-quality/notebooks/session3/mlruns_registry_demo/633445724452652697/models/m-905794ee8233405cb3348b16fbf235cb/artifacts
user_id: null
version: 2
