artifact_location: file:///home/boume/data-science-toolkit/air-quality/notebooks/session3/mlruns_registry_demo/0
creation_time: 1790507274703
experiment_id: '0'
last_update_time: 1790507274703
lifecycle_stage: active
name: Default
