aliases: []
creation_timestamp: 1790507278568
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1790507278568
metrics: null
model_id: m-7c1ec53c994847088e58e52a2932546d
name: toy_model
params: null
run_id: 1fa872ae3e62468a8882f2dce7c52e1e
run_link: null
source: models:/m-7c1ec53c994847088e58e52a2932546d
status: READY
status_message: null
storage_location: file:///home/boume/data-science-toolkit/air-quality/notebooks/session3/mlruns_registry_demo/633445724452652697/models/m-7c1ec53c994847088e58e52a2932546d/artifacts
user_id: null
version: 1
